version: '3.8'

services:
  app:
    build: .
    container_name: peluqueria-container
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/peluqueria
      - SESSION_SECRET=bellaimagenkey
      - PORT=3000
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6
    container_name: peluqueria-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:

